// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// internalBannerI18NDao is internal type for wrapping internal DAO implements.
type internalBannerI18NDao = *internal.BannerI18NDao

// bannerI18NDao is the data access object for table banner_i18n.
// You can define custom methods on it to extend its functionality as you wish.
type bannerI18NDao struct {
	internalBannerI18NDao
}

var (
	// BannerI18N is globally public accessible object for table banner_i18n operations.
	BannerI18N = bannerI18NDao{
		internal.NewBannerI18NDao(),
	}
)

// Fill with you ideas below.
