// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// internalProductCategoryDao is internal type for wrapping internal DAO implements.
type internalProductCategoryDao = *internal.ProductCategoryDao

// productCategoryDao is the data access object for table product_category.
// You can define custom methods on it to extend its functionality as you wish.
type productCategoryDao struct {
	internalProductCategoryDao
}

var (
	// ProductCategory is globally public accessible object for table product_category operations.
	ProductCategory = productCategoryDao{
		internal.NewProductCategoryDao(),
	}
)

// Fill with you ideas below.
