// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// internalProductI18NDao is internal type for wrapping internal DAO implements.
type internalProductI18NDao = *internal.ProductI18NDao

// productI18NDao is the data access object for table product_i18n.
// You can define custom methods on it to extend its functionality as you wish.
type productI18NDao struct {
	internalProductI18NDao
}

var (
	// ProductI18N is globally public accessible object for table product_i18n operations.
	ProductI18N = productI18NDao{
		internal.NewProductI18NDao(),
	}
)

// Fill with you ideas below.
