// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// internalProductCategoryI18NDao is internal type for wrapping internal DAO implements.
type internalProductCategoryI18NDao = *internal.ProductCategoryI18NDao

// productCategoryI18NDao is the data access object for table product_category_i18n.
// You can define custom methods on it to extend its functionality as you wish.
type productCategoryI18NDao struct {
	internalProductCategoryI18NDao
}

var (
	// ProductCategoryI18N is globally public accessible object for table product_category_i18n operations.
	ProductCategoryI18N = productCategoryI18NDao{
		internal.NewProductCategoryI18NDao(),
	}
)

// Fill with you ideas below.
