// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// internalRecipeTagRelationDao is internal type for wrapping internal DAO implements.
type internalRecipeTagRelationDao = *internal.RecipeTagRelationDao

// recipeTagRelationDao is the data access object for table recipe_tag_relation.
// You can define custom methods on it to extend its functionality as you wish.
type recipeTagRelationDao struct {
	internalRecipeTagRelationDao
}

var (
	// RecipeTagRelation is globally public accessible object for table recipe_tag_relation operations.
	RecipeTagRelation = recipeTagRelationDao{
		internal.NewRecipeTagRelationDao(),
	}
)

// Fill with you ideas below.
