// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// internalRecipeI18NDao is internal type for wrapping internal DAO implements.
type internalRecipeI18NDao = *internal.RecipeI18NDao

// recipeI18NDao is the data access object for table recipe_i18n.
// You can define custom methods on it to extend its functionality as you wish.
type recipeI18NDao struct {
	internalRecipeI18NDao
}

var (
	// RecipeI18N is globally public accessible object for table recipe_i18n operations.
	RecipeI18N = recipeI18NDao{
		internal.NewRecipeI18NDao(),
	}
)

// Fill with you ideas below.
