// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// internalRecipeTagDao is internal type for wrapping internal DAO implements.
type internalRecipeTagDao = *internal.RecipeTagDao

// recipeTagDao is the data access object for table recipe_tag.
// You can define custom methods on it to extend its functionality as you wish.
type recipeTagDao struct {
	internalRecipeTagDao
}

var (
	// RecipeTag is globally public accessible object for table recipe_tag operations.
	RecipeTag = recipeTagDao{
		internal.NewRecipeTagDao(),
	}
)

// Fill with you ideas below.
