// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-admin/internal/dao/internal"
)

// internalRecipeDao is internal type for wrapping internal DAO implements.
type internalRecipeDao = *internal.RecipeDao

// recipeDao is the data access object for table recipe.
// You can define custom methods on it to extend its functionality as you wish.
type recipeDao struct {
	internalRecipeDao
}

var (
	// Recipe is globally public accessible object for table recipe operations.
	Recipe = recipeDao{
		internal.NewRecipeDao(),
	}
)

// Fill with you ideas below.
